"""initial schema

Revision ID: 507fea49478f
Revises: 
Create Date: 2026-09-09 22:06:26.413499
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '507fea49478f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('previous_state', sa.String(length=32), nullable=True),
    sa.Column('new_state', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_table('call_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_call_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('task_text', sa.Text(), nullable=True),
    sa.Column('task_structured_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('task_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_confidence_score', sa.Float(), nullable=True),
    sa.Column('completion_confidence_label', sa.String(length=32), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mock_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_call_batches_provider_call_id'), 'call_batches', ['provider_call_id'], unique=False)
    op.create_index(op.f('ix_call_batches_status'), 'call_batches', ['status'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone_e164', sa.String(length=20), nullable=False),
    sa.Column('ack_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_ship_date', sa.Date(), nullable=True),
    sa.Column('item_summary', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('recipient_blocklisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_exceptions_state'), 'exceptions', ['state'], unique=False)
    op.create_index('ix_exceptions_state_due', 'exceptions', ['state', 'ack_due_at'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_outbox_available_at'), 'outbox', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('provider_call_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_webhook_events_provider_call_id'), 'webhook_events', ['provider_call_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exception_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=True),
    sa.Column('call_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_exception_id'), 'policy_decisions', ['exception_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_workflow_run_id'), 'policy_decisions', ['workflow_run_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_attempt_no', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_exception_id'), 'workflow_runs', ['exception_id'], unique=False)
    op.create_table('call_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=False),
    sa.Column('call_batch_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider_recipient_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('structured_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recipient_status', sa.String(length=32), nullable=True),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_batch_id'], ['call_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', 'attempt_no', name='uq_attempt_per_run')
    )
    op.create_index(op.f('ix_call_attempts_call_batch_id'), 'call_attempts', ['call_batch_id'], unique=False)
    op.create_index(op.f('ix_call_attempts_provider_recipient_id'), 'call_attempts', ['provider_recipient_id'], unique=False)
    op.create_index(op.f('ix_call_attempts_workflow_run_id'), 'call_attempts', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_attempts_workflow_run_id'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_provider_recipient_id'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_call_batch_id'), table_name='call_attempts')
    op.drop_table('call_attempts')
    op.drop_index(op.f('ix_workflow_runs_exception_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_policy_decisions_workflow_run_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_exception_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_webhook_events_provider_call_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_available_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_exceptions_state_due', table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_state'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_call_batches_status'), table_name='call_batches')
    op.drop_index(op.f('ix_call_batches_provider_call_id'), table_name='call_batches')
    op.drop_table('call_batches')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
