"""persist call transcript

Revision ID: 615e117a40d6
Revises: dd07afdc26f3
Create Date: 2026-09-09 23:46:57.222316
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '615e117a40d6'
down_revision = 'dd07afdc26f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_attempts', sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_attempts', 'transcript')
    # ### end Alembic commands ###
