"""persist simulated provider events

Revision ID: dd07afdc26f3
Revises: fbc8d3e25a99
Create Date: 2026-09-09 23:34:15.969542
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'dd07afdc26f3'
down_revision = 'fbc8d3e25a99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_batches', sa.Column('mock_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_batches', 'mock_events')
    # ### end Alembic commands ###
