"""unique provider call id

Revision ID: fbc8d3e25a99
Revises: 507fea49478f
Create Date: 2026-09-09 23:00:52.819467
"""
from __future__ import annotations

from alembic import op


revision = 'fbc8d3e25a99'
down_revision = '507fea49478f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_batches_provider_call_id'), table_name='call_batches')
    op.create_index(op.f('ix_call_batches_provider_call_id'), 'call_batches', ['provider_call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_batches_provider_call_id'), table_name='call_batches')
    op.create_index(op.f('ix_call_batches_provider_call_id'), 'call_batches', ['provider_call_id'], unique=False)
    # ### end Alembic commands ###
